### ISSUE TITLE
编译的时候报错了

### ISSUE THREAD

**Issue by roc2539** [jindasong/vue-wechat-auth#1]
ERROR in static/js/vendor.7bfbb0eadf070df9a7be.js from UglifyJs
Unexpected token: name (vueWechatAuth) [./~/vue-wechat-auth/index.js:9,0][static/js/vendor.7bfbb0eadf070df9a7be.js:11521,4]

**Comment by roc2539** [comment]
hello有人用吗？

**Comment by slimcheng** [comment]
一样的错误

**Comment by mrsunx** [comment]
一样

**Comment by marderary** [comment]
在build/webpack.base.conf.js 文件中加入resolve('./node_modules/vue-wechat-auth')即可，完整代码如下
`{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'),resolve('./node_modules/vue-wechat-auth')]
      },`
